### ISSUE TITLE
Replace with REST API usage instead

### ISSUE THREAD

**Issue by Skarzee** [logicmonitor/lm_ruby#26]
Hey guys,

Since you have deprecated your RPC functionality is it possible to get these examples replaced by a list of functioning scripts that make use of your new REST API?

Thanks

**Comment by skt44** [comment]
Hi @Skarzee,

We're working on an SDK for our REST API that will be generated via Swagger Codegen. We plan to publish a Ruby SDK that will be used to replace the lm_ruby scripts, and expect this to happen in the next few months (current eta is late July). Our RPC API will remain available until the REST-based replacements are published. 

Thanks

**Comment by Skarzee** [comment]
As noted in the other module issues (for lm_python), we have had the RPC API enabled on our account until this happens.

Thanks again for your help. Closing this off. Perhaps some documentation updates on the 2 repos would be beneficial?
